// Date: 8/17/2014 11:35:34 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.HaitherecreeperMC.WoFMod;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

import org.lwjgl.opengl.GL11;

public class ModelBabyDragon extends ModelBase
{
  //fields
    ModelRenderer BackLeft;
    ModelRenderer FrontLeft;
    ModelRenderer BackRight;
    ModelRenderer FrontRight;
    ModelRenderer Neck1;
    ModelRenderer BackRightUL;
    ModelRenderer BackLeftUL;
    ModelRenderer FrontRightUL;
    ModelRenderer FrontLeftUL;
    ModelRenderer Tail3;
    ModelRenderer LWing4;
    ModelRenderer Nostril2;
    ModelRenderer Mouth1;
    ModelRenderer Mouth2;
    ModelRenderer Horn1;
    ModelRenderer Body;
    ModelRenderer Tail1;
    ModelRenderer Tail2;
    ModelRenderer Horn2;
    ModelRenderer Nostril1;
    ModelRenderer Neck2;
    ModelRenderer LWing1;
    ModelRenderer RWing1;
    ModelRenderer LWing;
    ModelRenderer LWing2;
    ModelRenderer LWing3;
    ModelRenderer RWing4;
    ModelRenderer RWing3;
    ModelRenderer RWing2;
    ModelRenderer RWing;
  
  public ModelBabyDragon()
  {
    textureWidth = 64;
    textureHeight = 32;
    
    BackLeft = new ModelRenderer(this, 24, 22);
    BackLeft.addBox(0F, 0F, 0F, 2, 5, 2);
    BackLeft.setRotationPoint(2F, 19F, -3.533333F);
    BackLeft.setTextureSize(64, 32);
    BackLeft.mirror = true;
    setRotation(BackLeft, 0F, 0F, 0F);
    FrontLeft = new ModelRenderer(this, 25, 4);
    FrontLeft.addBox(-1F, 0F, 0F, 2, 4, 2);
    FrontLeft.setRotationPoint(-2.5F, 20F, -3.533333F);
    FrontLeft.setTextureSize(64, 32);
    FrontLeft.mirror = true;
    setRotation(FrontLeft, 0F, 0F, 0F);
    BackRight = new ModelRenderer(this, 24, 22);
    BackRight.addBox(0F, 0F, 0F, 2, 5, 2);
    BackRight.setRotationPoint(2F, 19F, 1.466667F);
    BackRight.setTextureSize(64, 32);
    BackRight.mirror = true;
    setRotation(BackRight, 0F, 0F, 0F);
    FrontRight = new ModelRenderer(this, 25, 4);
    FrontRight.addBox(-1F, 0F, 0F, 2, 4, 2);
    FrontRight.setRotationPoint(-2.5F, 20F, 1.466667F);
    FrontRight.setTextureSize(64, 32);
    FrontRight.mirror = true;
    setRotation(FrontRight, 0F, 0F, 0F);
    Neck1 = new ModelRenderer(this, 45, 23);
    Neck1.addBox(-4.8F, 0F, -2F, 5, 4, 4);
    Neck1.setRotationPoint(-1.6F, 17.23333F, 0F);
    Neck1.setTextureSize(64, 32);
    Neck1.mirror = true;
    setRotation(Neck1, 0F, 0F, 1.301251F);
    BackRightUL = new ModelRenderer(this, 13, 23);
    BackRightUL.addBox(-1F, -2F, 0F, 3, 3, 2);
    BackRightUL.setRotationPoint(1.666667F, 19.33333F, 1.8F);
    BackRightUL.setTextureSize(64, 32);
    BackRightUL.mirror = true;
    setRotation(BackRightUL, 0F, 0F, -0.2230717F);
    BackLeftUL = new ModelRenderer(this, 13, 23);
    BackLeftUL.addBox(-1F, -2F, 0F, 3, 3, 2);
    BackLeftUL.setRotationPoint(1.7F, 19.3F, -3.833333F);
    BackLeftUL.setTextureSize(64, 32);
    BackLeftUL.mirror = true;
    setRotation(BackLeftUL, 0F, 0F, -0.2230717F);
    FrontRightUL = new ModelRenderer(this, 25, 4);
    FrontRightUL.addBox(-1F, 0F, 0F, 2, 4, 2);
    FrontRightUL.setRotationPoint(-3F, 16.93333F, 1.5F);
    FrontRightUL.setTextureSize(64, 32);
    FrontRightUL.mirror = true;
    setRotation(FrontRightUL, 0F, 0F, -0.1487144F);
    FrontLeftUL = new ModelRenderer(this, 25, 4);
    FrontLeftUL.addBox(-1F, 0F, 0F, 2, 4, 2);
    FrontLeftUL.setRotationPoint(-3F, 16.93333F, -3.5F);
    FrontLeftUL.setTextureSize(64, 32);
    FrontLeftUL.mirror = true;
    setRotation(FrontLeftUL, 0F, 0F, -0.1487144F);
    Tail3 = new ModelRenderer(this, 18, 11);
    Tail3.addBox(0.4666667F, -1.4F, -1.2F, 4, 1, 1);
    Tail3.setRotationPoint(9.666667F, 19.6F, 0.5333334F);
    Tail3.setTextureSize(64, 32);
    Tail3.mirror = true;
    setRotation(Tail3, 0F, 0F, -0.0743572F);
    LWing4 = new ModelRenderer(this, 24, 12);
    LWing4.addBox(-0.6F, -5.666667F, -0.5F, 1, 6, 1);
    LWing4.setRotationPoint(-1.566667F, 11.5F, -2.333333F);
    LWing4.setTextureSize(64, 32);
    LWing4.mirror = true;
    setRotation(LWing4, -1.078187F, 1.152537F, 1.896109F);
    Nostril2 = new ModelRenderer(this, 25, 14);
    Nostril2.addBox(-6.133333F, -3.8F, -1.733333F, 2, 1, 1);
    Nostril2.setRotationPoint(-2.9F, 7.666667F, -0.1333333F);
    Nostril2.setTextureSize(64, 32);
    Nostril2.mirror = true;
    setRotation(Nostril2, 0F, 0F, -0.1487144F);
    Mouth1 = new ModelRenderer(this, 44, 9);
    Mouth1.addBox(-6.133333F, -1.066667F, -1.733333F, 6, 2, 4);
    Mouth1.setRotationPoint(-3.2F, 9.133333F, -0.5F);
    Mouth1.setTextureSize(64, 32);
    Mouth1.mirror = true;
    setRotation(Mouth1, 0F, 0F, 0F);
    Mouth2 = new ModelRenderer(this, 44, 0);
    Mouth2.addBox(-6.133333F, -3.8F, -1.733333F, 6, 4, 4);
    Mouth2.setRotationPoint(-3.2F, 8.2F, -0.5F);
    Mouth2.setTextureSize(64, 32);
    Mouth2.mirror = true;
    setRotation(Mouth2, 0F, 0F, -0.1487144F);
    Horn1 = new ModelRenderer(this, 34, 0);
    Horn1.addBox(-6.133333F, -3.8F, -1.733333F, 4, 1, 1);
    Horn1.setRotationPoint(0.4666667F, 7.266667F, -0.6F);
    Horn1.setTextureSize(64, 32);
    Horn1.mirror = true;
    setRotation(Horn1, 0F, 0F, -0.1487144F);
    Body = new ModelRenderer(this, 13, 11);
    Body.addBox(0F, 0F, 0F, 9, 5, 5);
    Body.setRotationPoint(-4F, 14F, -2.533333F);
    Body.setTextureSize(64, 32);
    Body.mirror = true;
    setRotation(Body, 0F, 0F, 0.1487144F);
    Tail1 = new ModelRenderer(this, 18, 11);
    Tail1.addBox(0F, -1.4F, -1.2F, 5, 3, 3);
    Tail1.setRotationPoint(3.733333F, 17.73333F, -0.1333333F);
    Tail1.setTextureSize(64, 32);
    Tail1.mirror = true;
    setRotation(Tail1, 0F, 0F, 0.1487144F);
    Tail2 = new ModelRenderer(this, 18, 11);
    Tail2.addBox(0F, -1.4F, -1.2F, 4, 2, 2);
    Tail2.setRotationPoint(7.066667F, 18.8F, 0.2F);
    Tail2.setTextureSize(64, 32);
    Tail2.mirror = true;
    setRotation(Tail2, 0F, 0F, 0.0743572F);
    Horn2 = new ModelRenderer(this, 34, 3);
    Horn2.addBox(-6.133333F, -3.8F, -1.733333F, 4, 1, 1);
    Horn2.setRotationPoint(0.4666667F, 7.266667F, 2.6F);
    Horn2.setTextureSize(64, 32);
    Horn2.mirror = true;
    setRotation(Horn2, 0F, 0F, -0.1487144F);
    Nostril1 = new ModelRenderer(this, 25, 13);
    Nostril1.addBox(-6.133333F, -3.8F, -1.733333F, 2, 1, 1);
    Nostril1.setRotationPoint(-2.866667F, 7.666667F, 1.933333F);
    Nostril1.setTextureSize(64, 32);
    Nostril1.mirror = true;
    setRotation(Nostril1, 0F, 0F, -0.1487144F);
    Neck2 = new ModelRenderer(this, 48, 16);
    Neck2.addBox(-4.8F, -1.6F, -1.666667F, 4, 3, 3);
    Neck2.setRotationPoint(-5F, 14.56667F, 0.06666667F);
    Neck2.setTextureSize(64, 32);
    Neck2.mirror = true;
    setRotation(Neck2, 0F, 0F, 1.635859F);
    LWing1 = new ModelRenderer(this, 24, 12);
    LWing1.addBox(-0.6F, -4F, -1.033333F, 2, 4, 2);
    LWing1.setRotationPoint(-2.666667F, 15.2F, -1.166667F);
    LWing1.setTextureSize(64, 32);
    LWing1.mirror = true;
    setRotation(LWing1, 0.2974216F, 0F, 0.1487144F);
    RWing1 = new ModelRenderer(this, 24, 12);
    RWing1.addBox(-0.6F, -4F, -1.033333F, 2, 4, 2);
    RWing1.setRotationPoint(-2.666667F, 15.16667F, 1.3F);
    RWing1.setTextureSize(64, 32);
    RWing1.mirror = true;
    setRotation(RWing1, -0.2974289F, 0F, 0.1487144F);
    LWing = new ModelRenderer(this, 4, 3);
    LWing.addBox(-0.6F, -6.666667F, 0F, 8, 7, 0);
    LWing.setRotationPoint(-1.566667F, 11.5F, -2.533333F);
    LWing.setTextureSize(64, 32);
    LWing.mirror = true;
    setRotation(LWing, 0.1844782F, 0F, 0.1487195F);
    LWing2 = new ModelRenderer(this, 24, 12);
    LWing2.addBox(-0.6F, -6.666667F, -0.5F, 1, 7, 1);
    LWing2.setRotationPoint(-1.566667F, 11.5F, -2.333333F);
    LWing2.setTextureSize(64, 32);
    LWing2.mirror = true;
    setRotation(LWing2, 0.2230643F, 0F, 0.1487144F);
    LWing3 = new ModelRenderer(this, 24, 12);
    LWing3.addBox(-0.6F, -5.666667F, -0.5F, 1, 6, 1);
    LWing3.setRotationPoint(-1.566667F, 11.5F, -2.333333F);
    LWing3.setTextureSize(64, 32);
    LWing3.mirror = true;
    setRotation(LWing3, 0.2602429F, -0.1115358F, 0.8551081F);
    RWing4 = new ModelRenderer(this, 24, 12);
    RWing4.addBox(-0.6F, -6.666667F, -0.5F, 1, 7, 1);
    RWing4.setRotationPoint(-1.533333F, 11.5F, 2.5F);
    RWing4.setTextureSize(64, 32);
    RWing4.mirror = true;
    setRotation(RWing4, 1.119902F, -1.133948F, 1.821752F);
    RWing3 = new ModelRenderer(this, 24, 12);
    RWing3.addBox(-0.6F, -6.666667F, -0.5F, 1, 7, 1);
    RWing3.setRotationPoint(-1.533333F, 11.5F, 2.5F);
    RWing3.setTextureSize(64, 32);
    RWing3.mirror = true;
    setRotation(RWing3, -0.2897247F, 0.1858931F, 0.8922821F);
    RWing2 = new ModelRenderer(this, 24, 12);
    RWing2.addBox(-0.6F, -6.666667F, -0.5F, 1, 7, 1);
    RWing2.setRotationPoint(-1.533333F, 11.5F, 2.5F);
    RWing2.setTextureSize(64, 32);
    RWing2.mirror = true;
    setRotation(RWing2, -0.2216568F, 0F, 0.1487144F);
    RWing = new ModelRenderer(this, 4, 3);
    RWing.addBox(-0.6F, -6.666667F, 0F, 8, 7, 0);
    RWing.setRotationPoint(-1.6F, 11.5F, 2.533333F);
    RWing.setTextureSize(64, 32);
    RWing.mirror = true;
    setRotation(RWing, -0.2216568F, 0F, 0.1487144F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    GL11.glPushMatrix();
    GL11.glRotatef(-90, 0, 1, 0);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    BackLeft.render(f5);
    FrontLeft.render(f5);
    BackRight.render(f5);
    FrontRight.render(f5);
    Neck1.render(f5);
    BackRightUL.render(f5);
    BackLeftUL.render(f5);
    FrontRightUL.render(f5);
    FrontLeftUL.render(f5);
    Tail3.render(f5);
    LWing4.render(f5);
    Nostril2.render(f5);
    Mouth1.render(f5);
    Mouth2.render(f5);
    Horn1.render(f5);
    Body.render(f5);
    Tail1.render(f5);
    Tail2.render(f5);
    Horn2.render(f5);
    Nostril1.render(f5);
    Neck2.render(f5);
    LWing1.render(f5);
    RWing1.render(f5);
    LWing.render(f5);
    LWing2.render(f5);
    LWing3.render(f5);
    RWing4.render(f5);
    RWing3.render(f5);
    RWing2.render(f5);
    RWing.render(f5);
    GL11.glPopMatrix();
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
    this.BackRight.rotateAngleZ = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
    this.BackLeft.rotateAngleZ = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
    this.BackRightUL.rotateAngleZ = MathHelper.cos(f * 0.6662F) * 1.4F * f1 + 45;
    this.BackLeftUL.rotateAngleZ = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1 + 45;
    this.FrontRight.rotateAngleZ = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
    this.FrontLeft.rotateAngleZ = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
  }

}
